#!/bin/bash

function init() {
	echo "---- fetch recipes ----"
	if [ -d bioconda-recipes ]; then
		echo "=> updating local repository"
		cd bioconda-recipes
		git pull --quiet
		cd ..
	else
		echo "=> cloning remote"
		git clone --quiet https://github.com/bioconda/bioconda-recipes.git
	fi

	echo "---- fetch repository data from anaconda ----"
	rm -f repodata.json repodata.json.bz2
	wget --quiet https://conda.anaconda.org/bioconda/linux-64/repodata.json.bz2
	bzip2 -d repodata.json.bz2
}

set -e
init

AFFECTED=$(./helpers.py)

if [ "$TRAVIS_SECURE_ENV_VARS" = "true" -a "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
	COMMANDS="all"

	echo "---- create repositories on quay ----"
	for i in $AFFECTED; do
		echo -n "* $i : "
		(
			echo "{"
			echo '"namespace": "'$NAMESPACE'",'
			echo '"visibility": "public",'
			echo '"description": "Auto-generated by [mulled/auto-mulled](https://github.com/mulled/auto-mulled)",'
			echo '"repository": "'$i'"'
			echo "}"
		) | curl --fail \
			-X POST \
			-HAuthorization:Bearer\ $QUAY_TOKEN \
			-d @- \
			-HContent-Type:application/json \
			https://quay.io/api/v1/repository \
			|| echo "  FAILED!"
		echo
	done

else
	COMMANDS="build"
fi

echo "---- package apps ----"

IFS=$'\n'
for i in $(./helpers.py $COMMANDS)
    do 
        echo 'Running the following command:' $i
        eval $i
    done
